# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from protocols import meu_qoelho_mq_pb2 as meu__qoelho__mq__pb2

GRPC_GENERATED_VERSION = '1.65.1'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.66.0'
SCHEDULED_RELEASE_DATE = 'August 6, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in meu_qoelho_mq_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class MeuQoelhoMqStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.createQueue = channel.unary_unary(
                '/MeuQoelhoMq/createQueue',
                request_serializer=meu__qoelho__mq__pb2.Queue.SerializeToString,
                response_deserializer=meu__qoelho__mq__pb2.Queue.FromString,
                _registered_method=True)
        self.removeQueue = channel.unary_unary(
                '/MeuQoelhoMq/removeQueue',
                request_serializer=meu__qoelho__mq__pb2.RemoveQueueRequest.SerializeToString,
                response_deserializer=meu__qoelho__mq__pb2.Empty.FromString,
                _registered_method=True)
        self.listQueues = channel.unary_unary(
                '/MeuQoelhoMq/listQueues',
                request_serializer=meu__qoelho__mq__pb2.Empty.SerializeToString,
                response_deserializer=meu__qoelho__mq__pb2.ListQueueResponse.FromString,
                _registered_method=True)
        self.publishMessages = channel.unary_unary(
                '/MeuQoelhoMq/publishMessages',
                request_serializer=meu__qoelho__mq__pb2.PublishMessagesRequest.SerializeToString,
                response_deserializer=meu__qoelho__mq__pb2.Empty.FromString,
                _registered_method=True)
        self.signToQueues = channel.unary_stream(
                '/MeuQoelhoMq/signToQueues',
                request_serializer=meu__qoelho__mq__pb2.SignToQueuesRequest.SerializeToString,
                response_deserializer=meu__qoelho__mq__pb2.SignToQueuesResponse.FromString,
                _registered_method=True)
        self.consumeMessageFromQueue = channel.unary_unary(
                '/MeuQoelhoMq/consumeMessageFromQueue',
                request_serializer=meu__qoelho__mq__pb2.ConsumeMessageRequest.SerializeToString,
                response_deserializer=meu__qoelho__mq__pb2.ConsumeMessageResponse.FromString,
                _registered_method=True)


class MeuQoelhoMqServicer(object):
    """Missing associated documentation comment in .proto file."""

    def createQueue(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def removeQueue(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def listQueues(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def publishMessages(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def signToQueues(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def consumeMessageFromQueue(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MeuQoelhoMqServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'createQueue': grpc.unary_unary_rpc_method_handler(
                    servicer.createQueue,
                    request_deserializer=meu__qoelho__mq__pb2.Queue.FromString,
                    response_serializer=meu__qoelho__mq__pb2.Queue.SerializeToString,
            ),
            'removeQueue': grpc.unary_unary_rpc_method_handler(
                    servicer.removeQueue,
                    request_deserializer=meu__qoelho__mq__pb2.RemoveQueueRequest.FromString,
                    response_serializer=meu__qoelho__mq__pb2.Empty.SerializeToString,
            ),
            'listQueues': grpc.unary_unary_rpc_method_handler(
                    servicer.listQueues,
                    request_deserializer=meu__qoelho__mq__pb2.Empty.FromString,
                    response_serializer=meu__qoelho__mq__pb2.ListQueueResponse.SerializeToString,
            ),
            'publishMessages': grpc.unary_unary_rpc_method_handler(
                    servicer.publishMessages,
                    request_deserializer=meu__qoelho__mq__pb2.PublishMessagesRequest.FromString,
                    response_serializer=meu__qoelho__mq__pb2.Empty.SerializeToString,
            ),
            'signToQueues': grpc.unary_stream_rpc_method_handler(
                    servicer.signToQueues,
                    request_deserializer=meu__qoelho__mq__pb2.SignToQueuesRequest.FromString,
                    response_serializer=meu__qoelho__mq__pb2.SignToQueuesResponse.SerializeToString,
            ),
            'consumeMessageFromQueue': grpc.unary_unary_rpc_method_handler(
                    servicer.consumeMessageFromQueue,
                    request_deserializer=meu__qoelho__mq__pb2.ConsumeMessageRequest.FromString,
                    response_serializer=meu__qoelho__mq__pb2.ConsumeMessageResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'MeuQoelhoMq', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('MeuQoelhoMq', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MeuQoelhoMq(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def createQueue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/MeuQoelhoMq/createQueue',
            meu__qoelho__mq__pb2.Queue.SerializeToString,
            meu__qoelho__mq__pb2.Queue.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def removeQueue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/MeuQoelhoMq/removeQueue',
            meu__qoelho__mq__pb2.RemoveQueueRequest.SerializeToString,
            meu__qoelho__mq__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def listQueues(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/MeuQoelhoMq/listQueues',
            meu__qoelho__mq__pb2.Empty.SerializeToString,
            meu__qoelho__mq__pb2.ListQueueResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def publishMessages(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/MeuQoelhoMq/publishMessages',
            meu__qoelho__mq__pb2.PublishMessagesRequest.SerializeToString,
            meu__qoelho__mq__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def signToQueues(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/MeuQoelhoMq/signToQueues',
            meu__qoelho__mq__pb2.SignToQueuesRequest.SerializeToString,
            meu__qoelho__mq__pb2.SignToQueuesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def consumeMessageFromQueue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/MeuQoelhoMq/consumeMessageFromQueue',
            meu__qoelho__mq__pb2.ConsumeMessageRequest.SerializeToString,
            meu__qoelho__mq__pb2.ConsumeMessageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
