# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: meu-qoelho-mq.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13meu-qoelho-mq.proto\"H\n\x05Queue\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x18\n\x04type\x18\x02 \x01(\x0e\x32\n.QueueType\x12\x17\n\x0fpendingMessages\x18\x03 \x01(\x05\"\"\n\x12RemoveQueueRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"+\n\x11ListQueueResponse\x12\x16\n\x06queues\x18\x01 \x03(\x0b\x32\x06.Queue\"I\n\x0bMessageType\x12\x16\n\x0ctext_message\x18\x01 \x01(\tH\x00\x12\x17\n\rbytes_message\x18\x02 \x01(\x0cH\x00\x42\t\n\x07message\"K\n\x16PublishMessagesRequest\x12\x11\n\tqueueName\x18\x01 \x01(\t\x12\x1e\n\x08messages\x18\x02 \x03(\x0b\x32\x0c.MessageType\"*\n\x13SignToQueuesRequest\x12\x13\n\x0bqueuesNames\x18\x01 \x03(\t\"H\n\x14SignToQueuesResponse\x12\x11\n\tqueueName\x18\x01 \x01(\t\x12\x1d\n\x07message\x18\x02 \x01(\x0b\x32\x0c.MessageType\"*\n\x15\x43onsumeMessageRequest\x12\x11\n\tqueueName\x18\x01 \x01(\t\"8\n\x16\x43onsumeMessageResponse\x12\x1e\n\x08response\x18\x01 \x01(\x0b\x32\x0c.MessageType\"\x07\n\x05\x45mpty*/\n\tQueueType\x12\x08\n\x04NONE\x10\x00\x12\n\n\x06SIMPLE\x10\x01\x12\x0c\n\x08MULTIPLE\x10\x02\x32\xcd\x02\n\x0bMeuQoelhoMq\x12\x1f\n\x0b\x63reateQueue\x12\x06.Queue\x1a\x06.Queue\"\x00\x12,\n\x0bremoveQueue\x12\x13.RemoveQueueRequest\x1a\x06.Empty\"\x00\x12*\n\nlistQueues\x12\x06.Empty\x1a\x12.ListQueueResponse\"\x00\x12\x34\n\x0fpublishMessages\x12\x17.PublishMessagesRequest\x1a\x06.Empty\"\x00\x12?\n\x0csignToQueues\x12\x14.SignToQueuesRequest\x1a\x15.SignToQueuesResponse\"\x00\x30\x01\x12L\n\x17\x63onsumeMessageFromQueue\x12\x16.ConsumeMessageRequest\x1a\x17.ConsumeMessageResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'meu_qoelho_mq_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_QUEUETYPE']._serialized_start=559
  _globals['_QUEUETYPE']._serialized_end=606
  _globals['_QUEUE']._serialized_start=23
  _globals['_QUEUE']._serialized_end=95
  _globals['_REMOVEQUEUEREQUEST']._serialized_start=97
  _globals['_REMOVEQUEUEREQUEST']._serialized_end=131
  _globals['_LISTQUEUERESPONSE']._serialized_start=133
  _globals['_LISTQUEUERESPONSE']._serialized_end=176
  _globals['_MESSAGETYPE']._serialized_start=178
  _globals['_MESSAGETYPE']._serialized_end=251
  _globals['_PUBLISHMESSAGESREQUEST']._serialized_start=253
  _globals['_PUBLISHMESSAGESREQUEST']._serialized_end=328
  _globals['_SIGNTOQUEUESREQUEST']._serialized_start=330
  _globals['_SIGNTOQUEUESREQUEST']._serialized_end=372
  _globals['_SIGNTOQUEUESRESPONSE']._serialized_start=374
  _globals['_SIGNTOQUEUESRESPONSE']._serialized_end=446
  _globals['_CONSUMEMESSAGEREQUEST']._serialized_start=448
  _globals['_CONSUMEMESSAGEREQUEST']._serialized_end=490
  _globals['_CONSUMEMESSAGERESPONSE']._serialized_start=492
  _globals['_CONSUMEMESSAGERESPONSE']._serialized_end=548
  _globals['_EMPTY']._serialized_start=550
  _globals['_EMPTY']._serialized_end=557
  _globals['_MEUQOELHOMQ']._serialized_start=609
  _globals['_MEUQOELHOMQ']._serialized_end=942
# @@protoc_insertion_point(module_scope)
